### ISSUE TITLE
Please provide requirements. txt

### ISSUE THREAD

**Issue by LianWu007** [apocas/restai#73]
The requirements.txt file is a text file used for Python projects, which lists all the required dependencies and their version numbers for the project.
![image](https://github.com/apocas/restai/assets/45118309/f80ebda6-5f1a-4a57-96bf-f949e0d097d2)
llama_index-0.10.14 is wrong
from llama_index.embeddings.langchain import LangchainEmbedding
from llama_index.postprocessor.colbert_rerank import ColbertRerank

**Comment by apocas** [comment]
This project uses [Poetry](https://python-poetry.org/)  to manage requirements.
Check the [pyproject.toml](https://github.com/apocas/restai/blob/master/pyproject.toml) file is where the requirements are specified.

There's also a [Makefile](https://github.com/apocas/restai/blob/master/Makefile) where you can check how the installation work.

Those errors in your screenshot are because your editor isn't using the venv that Poetry created after you ran `poetry install`.
